version: '3.8'

services:


  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    command: start-dev --import-realm
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export:/opt/keycloak/data/import
    depends_on:
      - ldap-hk
      - ldap-china
  ldap-hk:
    image: osixia/openldap:latest
    command: ["--copy-service"]
    container_name: ldap01
    environment:
      LDAP_ORGANISATION: "Org1"
      LDAP_DOMAIN: "org1.local"
      LDAP_ADMIN_PASSWORD: admin
    # ports:
    #   - "389:389"
    volumes:
      - ./org1/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif:ro

  ldap-china:
    image: osixia/openldap:latest
    command: ["--copy-service"]
    container_name: ldap02
    environment:
      LDAP_ORGANISATION: "Org2"
      LDAP_DOMAIN: "org2.local"
      LDAP_ADMIN_PASSWORD: admin
    # ports:
    #   - "389:389"
    volumes:
      - ./org2/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif:ro

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap1': [{'server': [{'tls': False}]}, {'login': [{'bind_id': 'cn=admin,dc=org1,dc=local'}, {'bind_pass': 'admin'}]}]}, {'ldap2': [{'server': [{'tls': False}]}, {'login': [{'bind_id': 'cn=admin,dc=org2,dc=local'}, {'bind_pass': 'admin'}]}]}]"
    ports:
      - "6443:443"
    depends_on:
      - ldap-hk
      - ldap-china
